/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pixelandbean.gui;

import javax.swing.table.DefaultTableModel;
import pixelandbean.model.Producto;
import pixelandbean.model.ProductoController;
/**
 *
 * @author Safagod
 */
public class MainFrame extends javax.swing.JFrame {
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private ProductoController productoController;
    /**
     * Creates new form MainFrame
     */
    
public MainFrame() {
    initComponents();
        productoController = new ProductoController(); 
        
        cargarTablaProductos();
        
        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.pack(); 
        
        System.out.println("MainFrame cargó correctamente");
    }
private void cargarTablaProductos() {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"ID", "Nombre", "Precio"}, 0
    );

    for (Producto p : productoController.getProductos()) {
        modelo.addRow(new Object[]{ p.getId(), p.getNombre(), p.getPrecio() });
    }

    tablaProductos.setModel(modelo);
}

public void actualizarTablaProductos() {
    cargarTablaProductos();
}
// REVISAR ESTO EN CHATGPT


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenido = new javax.swing.JPanel();
        lblEstado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenu();
        itemAgregarProducto = new javax.swing.JMenuItem();
        itemEditarProducto = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lblEstadoLayout = new javax.swing.GroupLayout(lblEstado);
        lblEstado.setLayout(lblEstadoLayout);
        lblEstadoLayout.setHorizontalGroup(
            lblEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lblEstadoLayout.setVerticalGroup(
            lblEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tablaProductos.setAutoCreateRowSorter(true);
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");
        jMenuBar1.add(menuArchivo);

        menuVentas.setText("Ventas");
        jMenuBar1.add(menuVentas);

        menuProductos.setText("Productos");

        itemAgregarProducto.setText("Agregar producto");
        itemAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarProductoActionPerformed(evt);
            }
        });
        menuProductos.add(itemAgregarProducto);

        itemEditarProducto.setText("Editar producto");
        itemEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarProductoActionPerformed(evt);
            }
        });
        menuProductos.add(itemEditarProducto);

        jMenuBar1.add(menuProductos);

        menuUsuarios.setText("Usuarios");
        jMenuBar1.add(menuUsuarios);

        menuAyuda.setText("Ayuda");
        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarProductoActionPerformed
       AgregarProductoFrame apf = new AgregarProductoFrame(productoController, this);
    apf.setVisible(true);
    }//GEN-LAST:event_itemAgregarProductoActionPerformed

    private void itemEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarProductoActionPerformed
    int fila = tablaProductos.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un producto en la tabla para editar.", "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Si la tabla tiene RowSorter (ordenamiento), convertir al índice del modelo
    int modeloRow = tablaProductos.convertRowIndexToModel(fila);

    // Obtener ID desde la columna 0 (asegúrate que la primera columna sea ID)
    Object idObj = tablaProductos.getModel().getValueAt(modeloRow, 0);
    int id;
    try {
        id = Integer.parseInt(String.valueOf(idObj));
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID inválido en la tabla", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Buscar producto en el controller
    pixelandbean.model.Producto p = productoController.buscarPorId(id);
    if (p == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Abrir la ventana de edición (constructor que ya creaste)
    EditarProductoFramee editar = new EditarProductoFramee(productoController, this, p);
    editar.setLocationRelativeTo(this);
    editar.setVisible(true);
    }//GEN-LAST:event_itemEditarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAgregarProducto;
    private javax.swing.JMenuItem itemEditarProducto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lblEstado;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
